### ISSUE TITLE
Feature: Add information about PR with unassigned issue to the contributing guidelines

### ISSUE THREAD

**Issue by adiati98** [open-sauced/docs#251]
### Type of feature

🍕 Feature

### Current behavior

We have an action that informs contributors when they are not assigned to the related issue of the PR. And this worth to add in the [Pull Requests (PR)](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#pull-requests-pr) section of our contributing guidelines for clarity.

Another thing, the `[!IMPORTANT]` in the section is not supported in docsify [as in GitHub](https://github.com/orgs/community/discussions/16925). So, we want to change this to bold instead.

### Suggested solution

In the [`docs/contributing/introduction-to-contributing.md`](https://github.com/open-sauced/docs/blob/main/docs/contributing/introduction-to-contributing.md):
1. Go to the "Pull Requests (PRs)" section
2. Fix things in the checklists below:

### Part 1

- [ ] Remove the first paragraph and replace with:

   ```markdown
   ---

   We actively welcome your pull requests. However, you must ensure that **you are assigned** to an existing issue before working on changes, and you need to **link your work to the issue** in your PR form.

   ---
   ```

   Line of code that needs to be changed:

   https://github.com/open-sauced/docs/blob/83e4fbc2e0d89da6805978f54a46826260913f57/docs/contributing/introduction-to-contributing.md?plain=1#L55

### Part 2

- [ ] In the second bullet point of point no. 9, remove the `<br />` and the following sentence.

   ```diff
   - - Unsolicited code is welcomed, but an issue is required to announce your intentions. <br /> **_PRs without a linked issue will be marked invalid and closed_**.
   + - Unsolicited code is welcomed, but an issue is required to announce your intentions.
   ```

    Line of code that needs to be changed:

   https://github.com/open-sauced/docs/blob/83e4fbc2e0d89da6805978f54a46826260913f57/docs/contributing/introduction-to-contributing.md?plain=1#L69

- [ ] After point no. 9, before `[!IMPORTANT]`, add this copy:

   ```markdown
   ⚠️ **PRs will be marked as invalid and may be closed if:**

   - the issue is not assigned to the contributor who opened the PR
   - no issue is linked to the PR
   ```

### Part 3

- [ ] Change the format of the word "IMPORTANT" as below:

   ```diff
   - > [!IMPORTANT]
   + > **IMPORTANT:**
   ```

   Line of code that needs to be changed:

   https://github.com/open-sauced/docs/blob/83e4fbc2e0d89da6805978f54a46826260913f57/docs/contributing/introduction-to-contributing.md?plain=1#L71

### Note

- Check the checklist as you work on your fix.
- Mention all the changes you made based on these checklists in your PR.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by DevJSter** [comment]
.take

**Comment by DevJSter** [comment]
Hey @adiati98 , I've completed all the tasks , Kindly whenever you're free check out my PR . Thanks.
