### ISSUE TITLE
Feature: Add posthog tracking to docusaurus

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#380]
### Suggested solution

Ref: https://posthog.com/docs/libraries/docusaurus

We want to track where users are reading at the very least. 

We currently know that we have ~7000 pageviews monthly to /docs. But we don't know where folks are going after they land on the site. 

Let's add docusaurus to our docs. As part of this, we want to track pageviews for the following:

1. Paths that fall in https://opensauced.pizza/docs/welcome/
2. Paths that fall in https://opensauced.pizza/docs/features/ (For now, we specifically want to know if there are pageviews on the following:
     - [ ] /features/workspaces/
     - [ ] /features/star-search/
     - [ ] /features/repo-insights/
     - [ ] /features/contributor-insights/
     - [ ] /features/repo-pages/
     - [ ] /features/highlights/
     - [ ] /features/dev-card/

**Comment by BekahHW** [comment]
@zeucapua if this issue doesn't fit in your bandwidth, feel free to reassign to me.
